- hosts: webservers
  gather_facts: yes
  tasks:
    - import_role:
        name: 'http-server'
      vars:
        service_name: "webserver-{{ inventory_hostname }}"

# NOTE: testing whether the first play was successful
- hosts: 127.0.0.1
  connection: local
  become: false
  gather_facts: false
  vars:
    host_port_mapping: '8080'
  tasks:
    - name: "verifying that Nginx is responsive"
      uri:
        url: "http://127.0.0.1:{{ host_port_mapping }}/health"
        timeout: 6
      register: response
      failed_when: response.status != 200
