all:
  vars:
    artifacts_dir: "{{ inventory_dir }}/../"

k8s-cluster:
  vars:
    kube_version: v1.20.2
    container_manager: 'containerd'
    kubeconfig_localhost: true
    dashboard_enabled: true
  children:
    kube-master: {}
    kube-node: {}

etcd:
  vars:
    etcd_deployment_type: host
