- hosts: instance_group
  gather_facts: yes
  collections:
    - 'ansible.builtin'
  tasks:
    - import_tasks: './tasks/install-nginx.yaml'
    - import_tasks: './tasks/install-podman.yaml'
    - import_tasks: './tasks/install-postgres.yaml'

  handlers:
    - import_tasks: './tasks/reload-nginx.yaml'
