- name: 'Installing Podman package repository'
  when: ansible_distribution == 'Ubuntu'
  block:
    - ansible.builtin.set_fact:
        ubuntu_major: "{{ ansible_distribution_version.split('.') | first }}"
        ubuntu_minor: "{{ ansible_distribution_version.split('.') | last }}"

    - when: ubuntu_major <= '20' and ubuntu_minor < '10'
      block:
        - name: 'Installing key for Podman apt repository'
          ansible.builtin.apt_key:
            url: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_{{ ansible_distribution_version }}/Release.key"
            state: present

        - name: 'Installing Podman apt repository'
          ansible.builtin.apt_repository:
            repo: "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_{{ ansible_distribution_version }}/ /"
            filename: 'devel:kubic:libcontainers:stable'
            state: present

- name: 'Installing Podman'
  ansible.builtin.apt:
    name:
      - podman
    state: present
