- name: 'Installing Nginx'
  ansible.builtin.package:
    name:
      - nginx
    state: present

- name: 'Disabling default vhost'
  ansible.builtin.file:
    state: absent
    path: '/etc/nginx/sites-enabled/default'
  notify:
    - 'Reloading Nginx'

- name: 'Configuring custom vhost'
  ansible.builtin.template:
    src: 'vhost.conf.j2'
    dest: "{{ nginx_conf_path }}/{{ fqdn | default('vhost') }}.conf"
    owner: 'root'
    group: 'root'
    mode: '644'
  notify:
    - 'Reloading Nginx'

- name: 'Define empty upstream, otherwise Nginx wont start'
  ansible.builtin.template:
    src: 'upstream.conf.j2'
    dest: "{{ nginx_conf_path }}/{{ service_name | default('upstream') }}.conf"
    owner: 'root'
    group: 'root'
    mode: '644'
  notify:
    - 'Reloading Nginx'

- name: 'Starting Nginx'
  ansible.builtin.service:
    name: nginx
    enabled: yes
    state: started
