nameOverride: ""
fullnameOverride: ""

image:
  registry: 'docker.io'
  repository: 'hackmdio/hackmd'
  tag: 'latest'

replicaCount: 1
port: 3000

# NOTE: provided via command line option
# fqdn: example.com

envVars:
  CMD_USECDN: 'false'
  CMD_PROTOCOL_USESSL: 'true'
  CMD_ALLOW_ANONYMOUS: 'true'
  CMD_ALLOW_ANONYMOUS_VIEWS: 'true'
  CMD_ALLOW_ANONYMOUS_EDITS: 'true'
  CMD_DEFAULT_PERMISSION: 'freely'

resources:
  requests:
    cpu: 256m
    memory: 256Mi
  limits:
    cpu: 512m
    memory: 512Mi

podSecurityContext: {}

securityContext:
  allowPrivilegeEscalation: false
  privileged: false
  runAsUser: 1500       # ORIGIN: https://github.com/hackmdio/docker-buildpack/blob/2d998b0c7300cd4c57f546a82dfa9a0d174fcc50/runtime/Dockerfile#L6
  capabilities:
    drop:
      - ALL


service:
  type: LoadBalancer
  port: 80


ingress:
  enabled: true
  annotations:
    # NOTE: enable session affinity to make websockets work for deployments with replica > 1
    nginx.ingress.kubernetes.io/affinity: 'cookie'


postgresql:
  fullnameOverride: 'postgres'
  postgresqlDatabase: 'my-db'
  service:
    port: 5432
  persistence:
    enabled: true
    existingClaim: 'pvc-db'
