workflow:
  rules:
    # NOTE: run pipeline if commit is to a Merge/Pull-Request
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    # NOTE: run pipeline if commit is directly pushed to certain branches
    - if: >-
        $CI_PIPELINE_SOURCE == "push"
        && ($CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "stable")
      when: always
    # NOTE: Otherwise
    - when: never

variables:
  version: 0.0.$CI_PIPELINE_IID

stages:
  - test
  - build
  - publish


job_test:
  stage: test
  image: registry.hub.docker.com/library/golang:1.21
  script:
    - go get -t ./...
    - go test -race -v ./...


job_build:
  stage: build
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /stable/
      when: always
  image: registry.hub.docker.com/library/golang:1.21
  script:
    - go get -t ./...
    - go build -o ./artifact.bin ./*.go
  artifacts:
    paths:
      - ./artifact.bin
    expire_in: 10 sec


job_upload:
  stage: publish
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /stable/
      when: always
  image: public.ecr.aws/lts/ubuntu:22.04
  tags:
    - docker-privileged
  dependencies:
    - job_build
  before_script:
    - apt update
    - apt install -y
        ca-certificates
        curl
    - update-ca-certificates
  script:
    - |
      curl \
        --header "JOB-TOKEN: ${CI_JOB_TOKEN}" \
        --upload-file ./artifact.bin \
        "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/artifacts/${version}/webservice"
