{{ if .Values.enablePersistence }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{{ include "chart.fullname" . }}-uploads'
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
{{ end }}
