- hosts: webservers
  gather_facts: yes
  tasks:
    - import_role:
        name: nginx
      vars:
        service_name: "nginx-{{ inventory_hostname }}"

- hosts: 127.0.0.1
  connection: local
  become: false
  gather_facts: false
  vars:
    host_port_mapping: '8080'
  tasks:
    - name: "verifying that Nginx is responsive"
      uri:
        url: "http://127.0.0.1:{{ host_port_mapping }}/healthz"
        timeout: 6
      register: response
      failed_when: response.status != 200
